// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAOME0EeYhyQGVlOQqZHLPCfIppLaCtdhs",
      authDomain: "innovasun-37ddf.firebaseapp.com",
      projectId: "innovasun-37ddf",
      storageBucket: "innovasun-37ddf.appspot.com",
      messagingSenderId: "1030577391684",
      appId: "1:1030577391684:web:d9f0ca279c1aa9c7d99411",
      measurementId: "G-1RQJXBZDFQ");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Ts6tD3TTetuizrW3KdY7ocC6Vs8dBLo',
    appId: '1:199985864773:android:aa61c66a13aea7c1d1c32c',
    messagingSenderId: '199985864773',
    projectId: 'nahbi-d4b87',
    storageBucket: 'nahbi-d4b87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7GqvwaqAUvuEtfqEDh01vwxP-v9KDjEE',
    appId: '1:199985864773:ios:a18a96cb4da42114d1c32c',
    messagingSenderId: '199985864773',
    projectId: 'nahbi-d4b87',
    storageBucket: 'nahbi-d4b87.appspot.com',
    iosClientId:
        '199985864773-63bht37a3iepdkh5aqjmo24t26al7ocn.apps.googleusercontent.com',
    iosBundleId: 'com.example.nahbi',
  );
}
